site_name: Programming Principles and Practice using C++ Solutions
repo_url: https://github.com/fjp/ppp/
nav:
  - 'test.md'
  - 'index.md'
markdown_extensions:
    - markdown_include.include:
        base_path: docs
        
# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
